version: '3'

services:

  # Front End Service ------------------------------------------------------------
  # front-end:
  #   build:
  #     context: ./../front-end
  #     dockerfile: ./../front-end/front-end-service.dockerfile
  #   ports:
  #     - "3000:80"
  #   restart: always
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  # Broker Service ---------------------------------------------------------------
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    ports:
      - "8080:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  # Authentication Service -------------------------------------------------------
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - "8081:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  # PostgreSQL Service -----------------------------------------------------------
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
